#!/usr/bin/env bash

## VARIABLES
THIS_DIR=$(cd "$(dirname "$0")"; pwd)
TDCLI='https://valtman.name/files/telegram-cli-1222'

## Print Colorful
# Print text in red
prtred() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
# Print text in green
prtgrn() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
# Print text in brown
prtbrown() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}
# update data to the last version
update() {
  git fetch --all && git reset --hard origin/persian && git pull origin persian && chmod +x BANG
    prtgrn "
      بروزرسانی اطلاعات با موفقیت انجام شد <<
  >> Tabchi's source successfully updated
"
}
# Create a new Tabchi
create() {
  name=BANG
  if [[ -e $name.lua ]] ; then
      i=1
      while [[ -e $name-$i.lua ]] ; do
          let i++
      done
      name=$name-$i
  fi
  cat BANG.lua >> "$name".lua
  sed -i 's/BANG-ID/'$i'/g' "$name".lua
    prtgrn "
     ربات شماره "$i" ساخته شد <<
  : رباتتان را با فرمان زیر اجرا کنید
>> new Tabchi seccessfuly created
       Tabchi number "$i"
      run your Tabchi by :"
prtred "
       ./BANG "$i"
"
}
# Create a new Tabchi manually
createmanual() {
   prtgrn '
        برای ساخت ربات با شماره دلخواه، شماره دلخواه خود را وارد کنید <<
  >> To creating a new Tabchi manually, Inter the Tabchi-ID :
'
  read -rp ' ' ID
    if [[ -e BANG-"$ID".lua ]] ; then
      prtred '
     شماره ربات وارد شده از قبل وجود دارد <<
  >> There is a Tabchi with this number ID
'
      exit
    else
      if [[ "$ID" =~ ^[0-9]+$ ]] ; then
        cat BANG.lua >> BANG-"$ID".lua
        sed -i 's/BANG-ID/'$ID'/g' BANG-"$ID".lua
        prtgrn "
     ربات شماره "$ID" ساخته شد <<
    : رباتتان را با فرمان زیر اجرا کنید
  >> new Tabchi seccessfuly created
       Tabchi number "$ID"
      run your Tabchi by :"
        prtred "
             ./BANG "$ID"
      "
      else
        prtred "
     شماره ربات را وارد کنید -- عدد
  Inter the Tabchi number --integer
    "
        exit
      fi
    fi
}
# Reset data to the last update
fix() {
  git reset --hard FETCH_HEAD
  prtgrn '
  بازیابی اطلاعات به آخرین آپدیت انجام شد <<
  >> Database Reseted and Fixed
'
}
# autolauncher
autolaunch() {
  while true ; do
    for sami in BANG-*.lua ; do
      tab="${sami%.*}"
      ltab="${tab/-/ }"
      tmux kill-session -t $tab
      for tg in ~/.telegram-cli/$tab/data/* ; do
        rm -rf $tg/*
      done
      TMUX= tmux new-session -d -s $tab "./$ltab"
      tmux detach -s $tab
    done
    echo -e " \n\e[1;32mربات ها راه اندازی شدند << \e[1;34m| NoFooZiTM |\e[1;32m>> Tabchis are Running\n\e[0;39;49m"
    sleep 1200
  done 
}
# clear a Tabchi
clear() {
  sudo service redis-server start
  prtgrn '
       : شماره شناسه تبجی بنگی که می‌خواهید پاک کنید را وارد کنید  <<
  >> Inter the Tabchi-ID,that you wanna delete :
'
  read -rp ' ' ID
  rm -rf ~/.telegram-cli/BANG-"$ID"/data
  rm -rf BANG-"$ID".lua
  redis-cli --raw keys "BANG"$ID* | xargs redis-cli del
  prtgrn '
     ربات شماره '$ID' با موفقیت حذف شد <<
  >> Tabchi number '$ID' seccessfuly deleted.
'
  exit
}
# install Tabchi
install() {
  prtgrn '
         آیا قصد نصب پیش نیاز های ربات تبجی بنگ را دارید؟ بله|خیر <<
  >> Do you want to install Essentials of Tabchi? (Y/N):
'
  read -rp ' ' install
  case "$install" in
    Y|y|بله)
      prtgrn "
         telegram-cli بارگیری <<
 >> Fetching $TDCLI
"
      wget "$TDCLI" -O telegram-cli
      chmod +x telegram-cli
      prtgrn "
     ارتقای اطلاعات قدیمی <<
 >> Updating old packages
"
      sudo apt-get -y update && sudo apt-get -y upgrade 
      prtgrn "
        نصب بسته های پیش نیازی <<
 >> Installing Essentials packages
"
      sudo apt-get --force-yes install git wget screen tmux libconfig9 libevent-dev libjansson4 libstdc++6 lua-socket lua5.2 liblua5.2 make unzip redis-server software-properties-common g++
      sudo apt-get -y update && sudo apt-get -y upgrade
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y gcc-4.9 g++-4.9 && sudo update-alternatives —install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 —slave /usr/bin/g++ g++ /usr/bin/g++-4.9
      prtgrn "
 ارتقای بسته های نصب شده <<
 >> Updating packages
"
      sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove
      prtgrn "
      redis راه اندازی مجدد  <<
 >> Restarting redis service
"
      sudo service redis-server restart
      prtgrn '
      نصب پیش نیاز های ربات تبجی بنگ با موفقیت انجام شد << 
 >> Essentials of Tabchi bang successfully installed!
 '
      printf '\e[1;33mبسازید\e[1;32m ./BANG create \e[1;33mربات تبجی بنگ خود را با دستور <<\e[1;33m%s\n >>Create Your Tabchi with\e[1;32m ./BANG create\e[0;39;49m%s\n'
    ;;
    N|n|خیر)
      prtbrown '
        لغو عملیات
 Canceling the operation
 '
    ;;
    *)
      prtred '
    دستور اشتباه
  Wrong command
 '
      install
    ;;
  esac
}
# How to use this script
usage() {
printf "\e[1;36m"
  cat <<EOF
  
                    $0 [موارد استفاده  : [گزینه ها <<
                                        : گزینه ها
        شماره             راه اندازی ربات با این شماره 
  راه‌اندازی انتی کرش ربات‌با‌این‌شماره            aشماره
   بازیابی اطلاعات از اخرین بروزرسانی             fix
    نصب پیش نیاز های ربات تبجی بنگ           install
      بروزرسانی به آخرین نسخه ربات            update
                 ساخت ربات جدید           create
       ساخت ربات جدید بصورت دستی        createmanual
                   نمایش این متن            help
   راه‌اندازی تمام ربات ها هر 20 دقیقه          autolaunch
                  
>> Usage: $0 [options]
    Options:
      createmanual      Create a new Tabchi manually
      autolaunch        Launch all Tabchis every 20 mins
      NUMBER            Start Tabchi whit this ID number
      aNUMBER           Start Tabchi whit this ID number in anticrash mod
      install           Install of Tabchi
      create            Create a new Tabchi
      update            Update Tabchi source code
      help              Print this message
      fix               Reseting data
EOF
printf "%s\n\e[0;39;49m"
}
## MAIN ------------------------------------------------------------------------
# Make sure this script run inside Tabchi directory
cd "$THIS_DIR" || exit
case $1 in
  create)
    create
  ;;
  install)
    install
  ;;
  autolaunch)
    autolaunch
  ;;
  createmanual)
    createmanual
  ;;
  a*)
    id="${1/a/}"
    if [ -a "$THIS_DIR"/BANG-"$id".lua ]; then
      screen -x -s BANG-"$id" quit
      while true ; do
        screen -s BANG-"$id" ./telegram-cli -p BANG-"$id" -s BANG-"$id".lua
        sleep 10
      done
    else
      usage
    fi
  ;;
  clr)
    clear
  ;;
  *)
    if [ -a "$THIS_DIR"/BANG-"$1".lua ]; then
      ./telegram-cli -p BANG-"$1" -s BANG-"$1".lua
    else
    usage
    fi
  ;;
esac
